name: soundfont_kit
description: "A high-performance SoundFont (SF2, SF3, SFZ) reader and playback engine for Flutter."
publish_to: 'none'
version: 0.0.1
homepage: https://github.com/alnitak/soundfont_kit

environment:
  sdk: ^3.12.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^4.0.2
  path: ^1.9.0
  http: ^1.2.0
  flutter_soloud: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
